### ISSUE TITLE
NCryptOpenStorageProvider + KeyIso

### ISSUE THREAD

**Issue by kazuser** [AlexZIX/CNG-Explorer#1]
1. Создал ```Microsoft Software Key Storage Provider```:

![image](https://github.com/user-attachments/assets/574b335b-014c-4875-a6d3-339261c08e9b)

2. Сделал все свои грязные дела и потом освободил его:

![image](https://github.com/user-attachments/assets/77a0a6d1-5364-445f-b5e0-67ec854e88b5)

3. Допустим, во время моей работы в ```CNG-Explorer``` какое-то левое приложение или само сломалось, или что-то там поломало, сисадмину мгновенно ушёл алерт об этом и ему пришлось удалённо перезапустить службу ```KeyIso``` на моей системе, но он даже не смог уведомить меня об этом, потому что мой телефон вечно занят (я же обычный пользователь, и про этот инцидент вообще не в курсе, сижу себе работаю, по телефону болтаю и в ус не дую):

![image](https://github.com/user-attachments/assets/e04973b3-0e11-4990-ac9e-0c70d7f11dca)

4. В итоге у меня теперь **все попытки повторно создать новый провайдер после перезапуска службы заканчиваются ошибкой** о некорректном хэндле ("0x80070006") — естественно, я в этом (как пользователь, не желающий разбираться в истинных причинах) виню ```CNG-Explorer``` (потому что минуту назад всё работало прекрасно!):

![image](https://github.com/user-attachments/assets/bfd5819d-b0b6-48e5-b5c2-43eacb23fbcf)

Вопрос: есть идеи, как после перезапуска зависимой службы можно пересоздать/перерегистрировать провайдера **без перезапуска приложения**?

**Comment by kazuser** [comment]
Автоответ: похоже, что такое поведение является [системным ограничением](https://stackoverflow.com/a/78910051/2689204), и его никак не обойти и не решить. Что (на мой дилетантский взгляд, конечно) выглядит весьма и весьма странно: получается, чтобы нарушить работу любого завязанного на эту службу п/о (или даже о/с) — достаточно просто её (службу) перезапустить, и всё встаёт колом, потому что потом нужно будет обязательно перезапустить зависимое приложение, а в случае с Windows Hello ещё и саму систему перезагрузить потребуется. И это, б°°°ь, какой-то п°°°°ц, а не костыль.

Я не понимаю, в чём сложность повторного подключения клиента даже после рестарта службы. Проверяются ведь в  итоге сами входящие данные (ключ, серт, что там ещё по списку), а не handle самого отправителя (который один хрен можно в любой момент сбросить через `NCryptFreeObject`).

Ну, это так, мысли вслух. Спасибо ещё раз за наглядный пример, но где и как его теперь использовать, учитывая всё вышеперечисленное, пока не знаю...

**Comment by AlexZIX** [comment]
@kazuser Ну если хэндл кешируется во внешней библиотеке и релизится только при её выгрузке, то можно загружать её динамически и при необходимости выгружать вручную. Но я не думаю, что служба KeyIso перезапускается так часто, что это станет какой-то проблемой.

**Comment by kazuser** [comment]
> @kazuser Ну если хэндл кешируется во внешней библиотеке и релизится только при её выгрузке, то можно загружать её динамически и при необходимости выгружать вручную. Но я не думаю, что служба KeyIso перезапускается так часто, что это станет какой-то проблемой.

Нет, к сожалению, сброс/обнуление хэндла после рестарта службы не работает — в этом и засада.

**Comment by AlexZIX** [comment]
> > @kazuser Ну если хэндл кешируется во внешней библиотеке и релизится только при её выгрузке, то можно загружать её динамически и при необходимости выгружать вручную. Но я не думаю, что служба KeyIso перезапускается так часто, что это станет какой-то проблемой.
> 
> Нет, к сожалению, сброс/обнуление хэндла после рестарта службы не работает — в этом и засада.

Я имел ввиду, что надо посмотреть - если хэндл кешируется в ncryptprov.dll, которая грузится в контекст процесса, то никто не мешает её загружать/выгружать динамически через LoadLibrary и не трогать сам процесс. Надо просто попробовать.

**Comment by kazuser** [comment]
А как такой фокус провернуть? 🤔

**Comment by AlexZIX** [comment]
В папке common лежит файлик NCryptCNG.pas. В нём прописаны статически функции из ncrypt.dll. Нужно их оттуда забрать и грузить через LoadLibrary и GetProcAddress. При возникновении такой ситуации, выгружать через FreeLibrary. Она за собой и ncryptprov.dll должна выгрузить, так как она её и тянет, очистив кэш с хендлами, затем повторить процесс загрузки. 
Это в теории. На практике нужно пробовать.

**Comment by kazuser** [comment]
>На практике нужно пробовать

Есть возможность? Потому что я не совсем улавливаю суть этого фокуса 🥲
